# SQLite in gemountetem Volume
db_path = /var/lib/ham-bbs.db

# APRS-Daemon verbindet zu Host-Direwolf
aprs_host = 192.168.178.59
aprs_port = 8001

# BBS Telnet-Port
listen_port = 2323

bbs_name = AprSurf BBS (Container)
sysop_callsign = DN9RZ
bbs_callsign = DN9RZ-10
grid_locator = JO31EG
beacon_interval = 1200
#beacon_text = BBS telnet localhost 2323 or msg HELP
beacon_text = BBS: msg 'HELP' for commands.
gps_lat = 51.15
gps_lon = 6.22
